version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: zeroq-riven_frontend_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  server:
    image: spoked/riven:sha-06f5a78@sha256:08d9932dd1b4724b3c70057c3fbcdb79c4631b0eccfecbd64fb5556cce0ec5ff
    restart: on-failure
    stop_grace_period: 1m
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    shm_size: 1024m
    devices:
      - /dev/fuse
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      API_KEY: "0123456789abcdef0123456789abcdef"
      RIVEN_FORCE_ENV: "true"
      RIVEN_DATABASE_HOST: postgresql+psycopg2://postgres:postgres@zeroq-riven-postgres/riven
      RIVEN_FILESYSTEM_MOUNT_PATH: "/mount"
      RIVEN_UPDATERS_LIBRARY_PATH: "/mount"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/openapi.json >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ${APP_DATA_DIR}/data/riven:/riven/data
      - ${UMBREL_ROOT}/data/storage/downloads/riven:/mount:rshared
    depends_on:
      zeroq-riven-postgres:
        condition: service_healthy

  frontend:
    image: spoked/riven-frontend:sha-3c92981@sha256:14f43d3043d15e8fbd24d735f1771f94d85b52674afd62b5079ce843a41c3e45
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      TZ: Etc/UTC
      BACKEND_URL: "http://server:8080"
      BACKEND_API_KEY: "0123456789abcdef0123456789abcdef"
      DATABASE_URL: "/riven/data/riven.db"
      AUTH_SECRET: "${APP_SEED}"
      DISABLE_EMAIL_PASSWORD: "false"
      ENABLE_EMAIL_PASSWORD_SIGNUP: "true"
      HOST_HEADER: "host"
      PROTOCOL_HEADER: "x-forwarded-proto"
      ORIGIN: "${APP_ZEROQ_RIVEN_LOCAL_URL}"
    volumes:
      - ${APP_DATA_DIR}/data/frontend:/riven/data
    depends_on:
      server:
        condition: service_healthy

  zeroq-riven-postgres:
    image: postgres:17-alpine@sha256:778d0b486d6daa02b77434d0358ec57a1b21fd8b6d22ac2eef56a33e816928f6
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d riven"]
      interval: 10s
      timeout: 5s
      retries: 5
