version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: zeroq-riven_server_1
      APP_PORT: 8080

  server:
    image: spoked/riven:v0.23.6@sha256:03ab5d11a2d64832b990557a34f15c237dd5cbca7c31f830fd2cf073638b8aaa
    restart: on-failure
    stop_grace_period: 1m
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    shm_size: 1024m
    devices:
      - /dev/fuse
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      RIVEN_FORCE_ENV: "true"
      RIVEN_DATABASE_HOST: postgresql+psycopg2://postgres:postgres@zeroq-riven-postgres/riven
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ${APP_DATA_DIR}/data/riven:/riven/data
      - ${UMBREL_ROOT}/data/storage/downloads/riven:/mount:rshared
    depends_on:
      zeroq-riven-postgres:
        condition: service_healthy

  zeroq-riven-postgres:
    image: postgres:17-alpine@sha256:778d0b486d6daa02b77434d0358ec57a1b21fd8b6d22ac2eef56a33e816928f6
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d riven"]
      interval: 10s
      timeout: 5s
      retries: 5
