version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: zeroq-vortexo-bridge-server
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/zeroq-bit/vortexo-manifest-server:main@sha256:ba22e7c8e8843e8f6a642d76b8cdae97a9153d49826785c0dba0752d28349d1e
    restart: on-failure
    stop_grace_period: 30s
    environment:
      VORTEXO_LISTEN_ADDR: ":8080"
      VORTEXO_DATA_DIR: /data
      VORTEXO_ADMIN_USERNAME: vortexo
      VORTEXO_ADMIN_PASSWORD: vortexo
      TZ: Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      default:
        aliases:
          - zeroq-vortexo-bridge-server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
